name: Custom Windows VNC

on: 
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Getting Updates and Installing Tailscale, Git.
        run: |
          sudo apt update -y
          sudo apt install git wget -y
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up
          git clone https://github.com/jshruwyd/windows.git
          cd windows
          docker build -t dockerd .
      - name: Copying Docker Container Files and Setting Everything Up.
        run: |
          docker run -d --name windows --env VERSION="win10" --env RAM_SIZE="6G" --device /dev/kvm --cap-add NET_ADMIN -p 8006:8006 -p 3389:3389/tcp -p 3389:3389/udp --stop-signal SIGTERM dockurr/windows

          
